# Generated by Django 3.2.3 on 2021-05-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='device name')),
                ('password', models.CharField(max_length=50, verbose_name='PASSWORD')),
            ],
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
