# Generated by Django 3.2.3 on 2021-06-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0004_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='PseudoUser',
        ),
        migrations.AlterModelOptions(
            name='pseudouser',
            options={'verbose_name': 'ПсевдоЮзер', 'verbose_name_plural': 'ПсевдоЮзеры'},
        ),
    ]
