# Generated by Django 3.2.4 on 2021-07-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
