# Generated by Django 3.2.4 on 2021-07-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
