# Generated by Django 3.2.4 on 2021-08-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210730_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='data',
            new_name='lanes',
        ),
        migrations.AddField(
            model_name='project',
            name='bpm',
            field=models.IntegerField(default=120),
        ),
    ]
