# Generated by Django 3.2.4 on 2021-07-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.JSONField(default={'name': 'nonExi'}),
        ),
    ]
