# Generated by Django 3.2.4 on 2021-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0005_alter_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(default={'name': 'nonExi'}),
        ),
    ]
