# Generated by Django 3.2.4 on 2021-07-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0006_alter_project_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
    ]
