# Generated by Django 3.2.4 on 2021-07-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0007_remove_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(verbose_name={}),
        ),
    ]
