# Generated by Django 3.2.4 on 2021-07-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daw', '0008_alter_project_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='NoName', max_length=20),
        ),
    ]
